config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user/registrations', passwords: 'user/passwords',
  sessions: 'user/sessions'}
  root 'main#home'


  resources :posts do 
    resources :comments
  end 

  # resources :like, only: [:create, :destroy]
  post '/likes/action', to: "likes#action"

  delete "/posts/:id", to: "posts#destroy"
  # root "posts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path rou te ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes,  dependent: :destroy
  belongs_to :user
  has_one_attached :avatar

  # def self.method1
  #   # class method
  # end

  # def liked_by?
  #   p "Ok"
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # actions
  # new: tra ra view de tao post
  # create: khi minh an nut tao, no se submit form
  # link_to 'New post'

  before_action :authenticate_user!, expect: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC")  
  end

  def new
    @post = Post.new
  end

  def edit
   @post = Post.find(params[:id]) 
  end

  def update
   @post = Post.find(params[:id]) 
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def create
    # binding.pry
    # @post = Post.new(post_params)
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    # binding.pry
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
   
  def post_params 
    params.require(:post).permit(:title, :content, :avatar)
  end

  def authenticate_user!
    redirect_to new_user_session_path, alert: "you need to Sign In or Sign Up to continue" unless user_signed_in?
  end

end

app/views/posts/_form.html.erb
<style>
.post, .comment{
        width: 382px;
        overflow: hidden;
        margin: auto;
        margin: 20 0 0 450px;
        padding: 80px;
        background: #23463f;
        border-radius: 15px ;}
  p,h1,h2,h3,a{
  text-align: center;
  padding: 10px;
  }
body
  {
      margin: 0;
      padding: 0;
      background-color:#6abadeba;
      font-family: 'Arial';
  }

.center {
    display: flex;
    justify-content: center;
    gap: 10px;
    width: 382px;
        overflow: hidden;
        margin: auto;
        margin: 20 0 0 450px;
        padding: 80px;
        background: #23463f;
        border-radius: 15px ;
  }
.btn_link {
    text-decoration: none;
    border: 1px solid #000;
    background-color: green;
  }
.btn_link:link, .btn_link:visited {
    color: #6abadeba;
}
</style>


<body>

<div class="center">    
  <%= simple_form_for @post do |f| %> 
      <br />
      <br />
      <%= f.input :title, input_html: { class: 'input'}, wrapper: false, label_html: {class: 'label'}%>
      <br />
      <br />
      <%= f.input :content, input_html: { class: 'texterea'}, wrapper: false, label_html: {class: 'label'}%> 
      <br />
      <br />
      <%= f.file_field :avatar %>
      <br />
      <br />
      <% f.text_field :avatar %>
      <%= f.button :submit , class: "button is-primary", class: 'btn_link'%>
      <br />   
      <br />   
      <br />   
      <%= link_to "Back", posts_path, class: 'btn_link' %>
  <% end %>
</div>
  
</body>

app/views/posts/_likes.html.erb
<div class="like">
  <h2 class="subtitle is-5"><strong><%= post.likes.count %></strong> Likes </h2>
  <p><%= button_to "Like", likes_action_path(post_id: post.id), style: "background-color: #{params[:is_like] === "true" ? 'blue' : 'white'}" %></p>
</div><br /><br />

app/views/posts/edit.html.erb
<style>
  body
  {
      margin: 0;
      padding: 0;
      background-color:#6abadeba;
      font-family: 'Arial';
  }
  .center {
    display: flex;
    justify-content: center;
    gap: 10px;
    width: 382px;
        overflow: hidden;
        margin: auto;
        margin: 20 0 0 450px;
        padding: 80px;
        background: #23463f;
        border-radius: 15px ;
  }
  .btn_link {
    text-decoration: none;
    border: 1px solid #000;
    background-color: green;
  }

  .btn_link:link, .btn_link:visited {
    color: #6abadeba;
  }
  h1{
  text-align: center;
  padding: 10px;
  }
</style>

<body>
  <h1>EDIT POST</h1>
  <div class="center">  
    <%= simple_form_for @post do |f| %> 
        <br />
        <br />
        <%= f.input :title, input_html: { class: 'input'}, wrapper: false, label_html: {class: 'label'}%>
        <br />
        <br />
        <%= f.input :content, input_html: { class: 'texterea'}, wrapper: false, label_html: {class: 'label'}%> 
        <br />
        <br />
        <%= f.file_field :avatar %>
        <br />
        <br />
        <% f.text_field :avatar %>
        <%= f.button :submit , class: "button is-primary", class: 'btn_link'%>
        <br /> 
        <br />
        <%= link_to "Delete", @post, data: {"turbo-method": :delete, turbo_confirm: "Are you sure? "}, class: 'btn_link'%>  
        <br />   
        <br />   
        <%= link_to "Back", post_path, class: 'btn_link' %>
    <% end %>
  </div>


</body>

app/views/posts/index.html.erb
<style>
  p,h1,h2,a{
  text-align: center;
  padding: 10px;
  }
  body
  {
      margin: 0;
      padding: 0;
      background-color:#6abadeba;
      font-family: 'Arial';
  }
  .post{
        width: 382px;
        overflow: hidden;
        margin: auto;
        margin: 20 0 0 450px;
        padding: 80px;
        text-align: center;
        background: #23463f;
        border-radius: 15px ;
        justify-content: center;

}
  .btn_link {
    text-decoration: none;
    border: 1px solid #000;
    background-color: green;
  }

  .btn_link:link, .btn_link:visited {
    color: #6abadeba;
  }

  .center {
    display: flex;
    justify-content: center;
    gap: 10px;
    
  }
  </style>
  


  <h1>DINO BLOG</h1>
<section class="hero is-primary is-medium">
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu"></div>
        <div class="navbar-end center">
          <% if user_signed_in? %>
            <%= link_to "Create New Post", new_post_path, class: 'btn_link' %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class: 'btn_link' %>
            <%= link_to "Sign Up", new_user_registration_path, class: 'btn_link' %>
          <% end %>
            <%= link_to "Back", root_path, class: 'btn_link' %>
        </div>
      </div>
    </nav>
  </div>
</section>



<h2>All Post</h2>
<body>
        <% @posts.each do |post| %>
         <div class="post">
           <%= link_to post.title, post %>
           <br />
           <br />
           <br />
           <%= image_tag post.avatar, width: "200px" , height: "200px" if post.avatar.attached? %>  
           <br />
           <br />
           <br />       
           <%= post.content %>
         </div>
         <br />
         <br />
        <% end %>
 
</body>

app/views/posts/new.html.erb
<style>
    .btn_link {
    text-decoration: none;
    border: 1px solid #000;
    background-color: green;
  }

  .btn_link:link, .btn_link:visited {
    color: #6abadeba;
  }

  .center {
    display: flex;
    justify-content: center;
    gap: 10px;
  }
</style>
<h1>Create New Post</h1>


<%= render 'form'%>

app/views/posts/show.html.erb
<style>
  h1{
  text-align: center;
  padding: 10px;
  }
  body
  {
      margin: 0;
      padding: 0;
      background-color:#6abadeba;
      font-family: 'Arial';
  }
.comment{
        width: 382px;
        overflow: hidden;
        margin: auto;
        text-align: center;
        margin: 20 0 0 450px;
        padding: 80px;
        background: #23463f;
        border-radius: 15px ;

}

.like{
        width: 382px;
        overflow: hidden;
        margin: auto;
        text-align: center;
        margin: 20 0 0 10px;
        padding: 80px;
        background: #23463f;
        border-radius: 15px ;

}
.center {
    display: flex;
    justify-content: center;
    gap: 10px;
  }
  .btn_link {
    text-decoration: none;
    border: 1px solid #000;
    background-color: green;
  }
.post {
  width: 382px;
        overflow: hidden;
        margin: auto;
        margin: 20 0 0 450px;
        padding: 80px;
        text-align: center;
        background: #23463f;
        border-radius: 15px ;
        justify-content: center;
}
  .btn_link:link, .btn_link:visited {
    color: #6abadeba;
  }

</style>

<h1><%= @post.title%></h1>
<div class="post">
  <br />
  <% if @post.avatar.attached? %>
    <%= image_tag @post.avatar, width: "200px" , height: "200px" %>
    <br />
    <br />
  <% end %>
  <br />
  <br />
  <%= @post.content%>
  <br />
  <br />
  <div class="center">
  <%= link_to "Edit", edit_post_path(@post), class: 'btn_link' %>
  <br />
  <br />
  <%= link_to "Delete", @post, data: {"turbo-method": :delete, turbo_confirm: "Are you sure?"}, class: 'btn_link' %>
  <br />
  <br />
  <%= link_to "Back", posts_path , class: 'btn_link' %>
  </div>
</div>
<br />
<br />
  <%= render partial: "likes", locals: {post: @post}%>

  <div class="comment">
      <strong><%= @post.comments.count %></strong> Comments 
    <%= render @post.comments %>
      <hr />
      <h2>Create comment</h2>
      <%= render 'comments/form' %>
  </div>